### PR TITLE
[US117162] Change the `role` of multi-select-list from a grid into a list

### PR DESCRIPTION
**Pull request by adamsk34**

### CODE REVIEW

**Comment by jameswklassen** [comment]
Will this break existing uses of multi select?

**Comment by jstefaniuk-d2l** [comment]
"role" is generally just a hint for screen-readers to know how to read things out, so shouldn't break any of the functionality

**Comment by adamsk34** [comment]
> 
> 
> Will this break existing uses of multi select?

My understanding is that it shouldn't break existing uses of multi select because it is only changing how the screen reader interprets the elements, but I will double check

**Comment by jstefaniuk-d2l** [comment]
I think this can be merged and then tested as part of the larger applied filters PR, just make sure to bump the version (minor)
image

**Comment by adamsk34** [comment]
Are you saying it shouldn't be merged yet?

**Comment by jstefaniuk-d2l** [comment]
Merge it, just make sure to put `[increment minor]` into the commit message when you see this (after hitting merge or "squash and merge")

image

**Comment by jstefaniuk-d2l** [comment]
Otherwise it won't bump the version and the other repo won't pick up the changes

**Comment by adamsk34** [comment]
Okay. Should I wait for Chester, Adam, and Evan to review it also, or has it received enough review?

**Comment by jameswklassen** [comment]
Chester's on vacation until august 10th 😛  and isn't on our team anymore.

**Comment by jstefaniuk-d2l** [comment]
I'd say you can merge, one or two approvals is usually good unless you have a specific person you want to look at things, also this will be tested as part of something else, so in this case you don't need to wait for testing

**Comment by adamsk34** [comment]
This relates to this issue:
https://rally1.rallydev.com/#/detail/userstory/401795493580?fdp=true

**Pull request merged**
