### PR TITLE
Remove multi-select from attribute-picker

### PR DESCRIPTION
**Pull request by GZolla**
[JIRA](https://desire2learn.atlassian.net/browse/GAUD-7193)

### CODE REVIEW

**Comment by ChrisLabattD2L** [comment]
Some of the functionality seems to be missing or broken from what existed. So far this is what I've found:
- Clicking on an item initially doesn't show that it's focused (i.e. the blue ring doesn't show up)
- Clicking on the delete icon doesn't always delete, it just loses focus
- Previously, if you remove an item via backspace, the index it chooses is the previous item, while removing with the delete key focuses on the new item in that index
- Previously, if you're on the last item and you try to go to the next item, it would go to the input list and open the dropdown to add an item. But now the focus is locked into the item list
- Screen readers no longer seem to tell the user the number of list items that exist anymore when going between items

**Comment by ChrisLabattD2L** [comment]
So I managed to fix some of the issues locally but others were still being problematic, I ended up posting in the [#wc-tag-list](https://d2l.slack.com/archives/C01QBU9J6M8/p1732200819946659) channel about them, also asking if we even need to make this change in this component, so if something else worked for the time being, with the intention of making something better in the future. Not sure if we'd want to mention it to Dave and Jeff or not either, since I know they might also want to be involved in that.

**Comment by GZolla** [comment]
> So I managed to fix some of the issues locally but others were still being problematic, I ended up posting in the [#wc-tag-list](https://d2l.slack.com/archives/C01QBU9J6M8/p1732200819946659) channel about them, also asking if we even need to make this change in this component, so if something else worked for the time being, with the intention of making something better in the future. Not sure if we'd want to mention it to Dave and Jeff or not either, since I know they might also want to be involved in that.
Yeah, I also have something working I'll push in a bit just fixing the tests. I think most of the things you brought up in [#wc-tag-list](https://d2l.slack.com/archives/C01QBU9J6M8/p1732200819946659) are resolved but there is a lot of those that could be considered for the core component.

**Comment by ChrisLabattD2L** [comment]
Based on talks within my team, we've decided it's probably better to leave this component as it is for now and move it over with a simplified list item instead of using the tag list or the deprecated component. That change was made in at the same time as it being moved over, which is happening in [this PR](https://github.com/BrightspaceUI/labs/pull/454)

**Pull request closed without merging**
